name: deploy-factrank.org

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          lfs: true
          persist-credentials: true
      - name: Install
        run: cd ui && npm install
      - name: Deploy 🚀
        run: cd ui && npm run deploy
